preferred_syntax = :scss
http_path = '/'
css_dir = 'public/css'
sass_dir = 'public/sass'
# images_dir = 'assets/images'
# javascripts_dir = 'assets/javascripts'
relative_assets = false
# line_comments = true
# output_style = :compressed
sourcemap = true